---
title: "Lab3"
author: "Jia Lin Gao"
date: "25/08/2020"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#imports
library(tidyverse)
library(plotrix)
library(rlist)
library(gganimate)
theme_set(theme_bw())
library(av)
library(gifski)
```

```{r}
df_len <- 20
min <- -5
max <- 5
set.seed(50)
x0 <- rep(1, df_len)
x1 <- sample(seq(min, max), df_len, replace = TRUE)
x2 <- sample(seq(min, max), df_len, replace = TRUE)
df = data.frame(x0, x1, x2)
plot(df$x1, df$x2)
```

```{r}
b1 <- runif(1, -1, 1) 
b2 <- runif(1, -1, 1) 
c  <- runif(1, -0.2, 0.2) 
df <- df %>% 
  mutate(y = ifelse(b1*x1+b2*x2+c>0, 1, -1))

plot <- ggplot(data=df, mapping=aes(x = x1, y=x2, color=as.factor(y)))+
  geom_point()+
  geom_abline(intercept = -c/b2, slope = -b1/b2)

plot
```

```{r}
w <- c(0,0,0)
df$yhat <- rep(1, df_len)
iter = 100
weights <- list()
weights <- list.append(weights, c(0, w))
```

```{r}
for (val in seq(1, iter))
{
  for (idx in seq(1, df_len))
  {
    df <- mutate(df, yhat = ifelse(w[1]*x0+w[2]*x1+w[3]*x2>0, 1, -1))
    if (df$yhat[idx] != df$y[idx])
    {
      w = c(w[1]+df$y[idx], w[2]+df$y[idx]*df$x1[idx], w[3]+df$y[idx]*df$x2[idx])
      weights <- list.append(weights, c(val, w))
    }
  }
}

weights_df <- as.data.frame(do.call(rbind, weights))
colnames(weights_df) <- c("citer", "cc","cb1","cb2")
weights_df$ctime <- seq.int(nrow(weights_df))

```

```{r fig.show = "animate"}
plot <- ggplot(weights_df)+
  geom_abline(intercept = -c/b2, slope = -b1/b2, color = "red")+
  geom_abline(intercept = -w[1]/w[3], slope = -w[2]/w[3], color = "blue")+
  geom_abline(aes(intercept = -cc/cb2, slope = -cb1/cb2))+
  transition_states(ctime, transition_length = 10, state_length = 10) +
  labs(title = "Update: {next_state}") +
  geom_point(data=df, mapping=aes(x=x1, y=x2, colour = as.factor(y))) +
  labs(colour = "category")

animate(plot, fps = 5, duration = 15, end_pause = 50)
```
The algorithm takes 

```{r}
coin_exp <- function(n_coins, n_times){
  rand_indx <- sample(n_coins, 1)
  rolls <- replicate(n_times, sample(c(0, 1), n_coins, replace = TRUE))

  rolls_df <- as.data.frame(rolls) 
  rolls_df <- mutate(rolls_df, v = rowMeans(rolls_df))
  v1 <- rolls_df$v[1]
  v2 <- rolls_df$v[rand_indx]
  vmin_idx <- which(rolls_df$v==min(rolls_df$v))
  vmin <- rolls_df$v[vmin_idx[1]]
  return(c(v1, v2, vmin))
}

```

```{r}
n_trials = 1000
n_coins = 1000
n_times = 10
if (is.null(coin_result))
{
  coin_result <- replicate(n_trials, coin_exp(n_coins, n_times))
  coin_result_df <- as.data.frame(t(coin_result)) 
  colnames(coin_result_df) <- c("v1", "v2", "vmin")
}

coin_result_df_long <- coin_result_df %>% pivot_longer(c(v1, v2, vmin), names_to="Coin", values_to="v")
```


```{r}
ggplot(data=coin_result_df_long, mapping = aes(x=v, colour=Coin))+
  geom_histogram(position = "dodge", binwidth=0.1)
```

$\mu$ is 0.5 for all three of the selected coins


```{r}
hoff <- list()
for (e in seq(0, 1, 0.01))
{
  num_v1 <- sum(abs(coin_result_df$v1-0.5) > e)
  num_v2 <- sum(abs(coin_result_df$v2-0.5) >  e)
  num_vmin <- sum(abs(coin_result_df$vmin-0.5) > e)
  hoff <- list.append(hoff, c(e, 2*exp(-2*n_trials*e**2), num_v1/n_trials,num_v2/n_trials,num_vmin/n_trials))
}

hoff_df <- as.data.frame(do.call(rbind, hoff))
colnames(hoff_df) <- c("e", "bound", "v1", "v2", "vmin")

ggplot(data=hoff_df, mapping=aes(x=e))+
  geom_line(aes(y=bound))+
  geom_line(aes(y=v1), color='red')+
  geom_line(aes(y=v2), color='blue')+
  geom_line(aes(y=vmin), color='green')
```
Exercise 3
```{r}
make_df <- function(df_len=20, min=-5, max =5, b1, b2, b0, seed=50)
{
  set.seed(seed)
  x0 <- rep(1, df_len)
  x1 <- sample(seq(min, max), df_len, replace = TRUE)
  x2 <- sample(seq(min, max), df_len, replace = TRUE)
  df <- data.frame(x0, x1, x2) %>% 
  mutate(y = ifelse(b1*x1+b2*x2+b0>0, 1, -1))
  return(df)
}
```

```{r}
perceptron <- function(df, n_iter=100,w = runif(n = 3, min = -1, max = 1))
{
  df_len <- unlist(count(df))
  df$yhat <- rep(1, count(df))
  weights <- list()
  weights <- list.append(weights, c(0, w))
  for (iter in seq(1, n_iter))
  {
    for (idx in seq(1, df_len))
    {
      df <- mutate(df, yhat = ifelse(w[1]*x0+w[2]*x1+w[3]*x2>0, 1, -1))
      if (df$yhat[idx] != df$y[idx])
      {
        w = c(w[1]+df$y[idx], w[2]+df$y[idx]*df$x1[idx], w[3]+df$y[idx]*df$x2[idx])
        weights <- list.append(weights, c(iter, w))
      }
    }
  }
  weights_df <- as.data.frame(do.call(rbind, weights))
  colnames(weights_df) <- c("iter", "b0_hat","b1_hat","b2_hat")
  weights_df$ctime <- seq.int(nrow(weights_df))
  return(weights_df)
}
```

```{r}
percep_plot <- function(weights_df, df, b0, b1, b2)
{  
  w <- tail(weights_df, n=1)[2:4]
  plot <- ggplot(weights_df)+
  geom_abline(intercept = -b0/b2, slope = -b1/b2, color = "red")+
  geom_abline(intercept = as.numeric(-w[1]/w[3]), slope = as.numeric(-w[2]/w[3]), color = "blue")+
  geom_abline(aes(intercept = -b0_hat/b2_hat, slope = -b1_hat/b2_hat))+
  transition_states(ctime, transition_length = 10, state_length = 3) +
  labs(title = "Update: {next_state}") +
  geom_point(data=df, mapping=aes(x=x1, y=x2, colour = as.factor(y))) +
  labs(colour = "category")
  print(w, w[1], b0, b0_hat)
  return(plot)
}
```

```{r}
pred <- function(df, w)
{
  df <- mutate(df, yhat = ifelse(w[1]*x0+w[2]*x1+w[3]*x2>0, 1, -1))
  return(df)
}
```

```{r}
b1 <- runif(1, -1, 1) 
b2 <- runif(1, -1, 1) 
b0  <- runif(1, -0.2, 0.2) 


df_3a <- make_df(b1=b1, b2=b2, b0=b0, seed=12)
plot <- ggplot(data=df_3a, mapping=aes(x = x1, y=x2, color=as.factor(y)))+
  geom_point()+
  geom_abline(intercept = -b0/b2, slope = -b1/b2)
plot
```

```{r fig.show = "animate"}
weights_3b <- perceptron(df_3a)
plot_3b <- percep_plot(weights_3b, df_3a, b0, b1, b2)
animate(plot_3b, duration=20)
```
```{r}
b1 <- runif(1, -1, 1) 
b2 <- runif(1, -1, 1) 
b0  <- runif(1, -0.2, 0.2) 

df_3c <- make_df(b1=b1, b2=b2, b0=b0, seed=8008)
plot <- ggplot(data=df_3c, mapping=aes(x = x1, y=x2, color=as.factor(y)))+
  geom_point()+
  geom_abline(intercept = -b0/b2, slope = -b1/b2)
plot
```

```{r}
weights_3c <- perceptron(df_3c)
plot_3c <- percep_plot(weights_3c, df_3c, b0, b1, b2)
animate(plot_3c, duration=20)
```

```{r}
b1 <- runif(1, -1, 1) 
b2 <- runif(1, -1, 1) 
b0  <- runif(1, -0.2, 0.2) 

df_3d <- make_df(b1=b1, b2=b2, b0=b0, seed=24, df_len=100)
plot <- ggplot(data=df_3d, mapping=aes(x = x1, y=x2, color=as.factor(y)))+
  geom_point()+
  geom_abline(intercept = -b0/b2, slope = -b1/b2)
plot
```
```{r}
weights_3d <- perceptron(df_3d)
plot_3d <- percep_plot(weights_3d, df_3d, b0, b1, b2)
animate(plot_3d, duration=20)
```

```{r}
b1 <- runif(1, -1, 1) 
b2 <- runif(1, -1, 1) 
b0  <- runif(1, -0.2, 0.2) 

df_3e <- make_df(b1=b1, b2=b2, b0=b0, seed=24, df_len=1000)
plot <- ggplot(data=df_3e, mapping=aes(x = x1, y=x2, color=as.factor(y)))+
  geom_point()+
  geom_abline(intercept = -b0/b2, slope = -b1/b2)
plot
```
```{r}
weights_3e <- perceptron(df_3e)
plot_3e <- percep_plot(weights_3e, df_3e, b0, b1, b2)
animate(plot_3e, duration=20)
```