---
title: "Lab3"
author: "Jia Lin Gao"
date: "25/08/2020"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    number_sections: yes
editor_options:
  chunk_output_type: inline
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      cache = FALSE
                      )
```

```{r}
#imports
library(tidyverse)
library(plotrix)
library(rlist)
library(gganimate)
theme_set(theme_bw())
library(av)
library(gifski)
```

```{r}
Ein_linreg <- function(X, y, w){
  n <- nrow(X)
  p <- ncol(X)
  mse <- (1/n)*t(y-X%*%w)%*%(y-X%*%w)
  return(mse)
  }
```

```{r}
Ein_logreg <- function(X, y, w){
    n <- nrow(X)
    e_in <- (1/n)*sum(log(1+exp(-y*X%*%w)))
    return(e_in)
    }
```

```{r}
gEin_linreg <- function(X, y, w){
  n <- nrow(X)
  delta_Ein <- (2/n)*(t(X)%*%X%*%w-t(X)%*%y)
  return(delta_Ein)
  }
```

```{r}
gEin_logreg <- function(X, y, w){
    n <- nrow(X)
    delta_Ein <- (1/n) * colSums( sweep(X, 1, sig(X%*%w)-y, "*") )  
    #delta_Ein <- (1/N) * (y%*%w)/(1+exp(-t(y)%*%X%*%w))
    return(delta_Ein)
  }
```
######################################################################




#########################################################################
```{r}
Ein_linreg_sgd <- function(X, y, w){
  mse <- (y-X%*%w)**2
  return(mse)
  }
```

```{r}
Ein_logreg_sgd <- function(X, y, w){
    n <- nrow(X)
    e_in <- (1/n)*sum(1/(1+exp(-y*X%*%w)))
    return(e_in)
    }
```

```{r}
gEin_linreg_sgd <- function(X, y, w){
  pred <- t(X)%*%w
  delta_Ein <- -(y-pred)*X
  return(delta_Ein)
  }
```

```{r}
gEin_logreg_sgd <- function(X, y, w){
    n <- nrow(X)
    delta_Ein <- (1/n) * colSums( sweep(X, 1, y-sig(X%*%w), "*") )  
    #delta_Ein <- (1/N) * colSums(sweep(sweep(X, 1, y, "*"), 1, 1+exp(y*X%*%w), "/"))
    #delta_Ein <- (1/N) * (y%*%w)/(1+exp(-t(y)%*%X%*%w))
    return(delta_Ein)
  }
```
######################################################################################3


###########################################################################
```{r}
sig <- function(X)
{
  1/(1+exp(-X))
}
```



```{r}

GD <-function(X, y, Ein, gEin, w0, eta, precision, nb_iters){
  allw <-vector("list", nb_iters)
  cost <-numeric(nb_iters)
  allw[[1]] <- w0
  cost[1] <-Ein(X, y, allw[[1]])
  flag <- F
  for (idx in seq(2, nb_iters))
    {
     allw[[idx]] <- allw[[idx-1]] - eta*gEin(X, y, allw[[idx-1]])     
     cost[idx] <-Ein(X, y, allw[[idx]])
     delta <- abs(cost[idx]-cost[idx-1])
     if (precision > delta)
     {
       res <- list(allw = allw[1:idx], cost = cost[1:idx])
       flag <- T
       break
     }
  }
  if(flag == F)
  {
    res <- list(allw = allw, cost = cost)
  }
  return(res)
  }

```

```{r}

SGD <-function(X, y, Ein, gEin, w0, eta, precision, nb_iters){
  n <- nrow(X)
  allw <-vector("list", nb_iters*n)
  cost <-numeric(nb_iters*n)
  allw[[1]] <- w0
  cost[1] <-Ein(X, y, allw[[1]])
  flag <- F
  
  for (i in seq(1, nb_iters))
    {
     for (j in seq(1, n))
     {
       idx <- ((i-1)*n)+1+j 
       xn <- X[j, ]
       yn <- y[j]
       print("j")
       print(j)
       print("idx")
       print(idx)
       print("xn")
       print(xn)
       print("yn")
       print(yn)
       print("w")
       print(allw[[idx-1]])
       allw[[idx]] <- allw[[idx-1]] - eta/n*gEin(xn, yn, allw[[idx-1]])
       print("gEin")
       print(gEin(xn, yn, allw[[idx-1]]))
       cost[idx] <-Ein(X, y, allw[[idx]])
       print("cost")
       print(cost[idx])
       delta <- abs(cost[idx]-cost[idx-1])
       if (precision > delta)
       {
         print("flag")
         res <- list(allw = allw[1:idx], cost = cost[1:idx])
         flag <- T
         break
       }
     }
    if (flag == T){
      break
    }

    }
  if(flag == F)
  {
    res <- list(allw = allw, cost = cost)
  }
  return(res)
  }

```

```{r}
set.seed(1900)# Function taken from Friedman et al.
genx <-function(n,p,rho){
  #    generate x's multivariate normal with equal corr rho
  # Xi = b Z + Wi, and Z, Wi are independent normal.
  # Then Var(Xi) = b^2 + 1
  #  Cov(Xi, Xj) = b^2  and so cor(Xi, Xj) = b^2 / (1+b^2) = rho
  z <-rnorm(n)
  if(abs(rho)<1){
    beta <-sqrt(rho/(1-rho))
    x <-matrix(rnorm(n*p), ncol=p)
    A <-matrix(rnorm(n), nrow=n, ncol=p, byrow=F)
    x <- beta*A+x}
  if(abs(rho)==1){ 
    x=matrix(rnorm(n),nrow=n,ncol=p,byrow=F)
    }
  return(x)
}
```

###############
GD Linear
################
```{r}

N <- 100
p <- 10
rho <- 0.2
X <-genx(N, p, rho)
w_true <- ((-1)^(1:p))*exp(-2*((1:p)-1)/20)
eps <-rnorm(N)
k <- 3
y <- X%*%w_true+k*eps
res <-GD(X, y, Ein_linreg, gEin_linreg,
         w0=rep(0, p), 
         eta=0.01, 
         precision=0.0001, 
         nb_iters=10000)
plot(res$cost)
print(w_true)
print(unlist(tail(res$allw, 1)))
```

##############
SGD Linear
##############

```{r}
N <- 100
p <- 10
rho <- 0.2
X <-genx(N, p, rho)
w_true <- ((-1)^(1:p))*exp(-2*((1:p)-1)/20)
eps <-rnorm(N)
k <- 3
y <- X%*%w_true+k*eps
res <-SGD(X, y, Ein_linreg_sgd, gEin_linreg_sgd,
         w0=rep(0, p), 
         eta=0.0001, 
         precision=0.0001, 
         nb_iters=100)
plot(res$cost)
print(w_true)
print(unlist(tail(res$allw, 1)))
```
###############

GD Logistic
################
```{r}
set.seed(1900)
N <- 100
l <--5; u <- 5
x <-seq(l, u, by = 0.1)
w_true <-matrix(c(-3, 1, 1), ncol = 1)
a <--w_true[2]/w_true[3]
b <--w_true[1]/w_true[3]
X0 <-matrix(runif(2*N, l, u), ncol = 2)
X <-cbind(1, X0)
y <-sign(X%*%w_true)
```

```{r}
res <-GD(X, y, Ein_logreg, gEin_logreg,          
         w0=c(0, 0, 0), 
         eta=0.05, 
         precision=0.0001, 
         nb_iters=10000)
plot(res$cost)
print(w_true)
w_best <-unlist(tail(res$allw,1))
print(w_best)
plot(c(l, u),c(u, l),type ='n',xlab ="x1", ylab ="x2")
lines(x, a*x+b)
points(X0,col =ifelse(y==1, "red", "blue"))
a_best <--w_best[2]/w_best[3]
b_best <--w_best[1]/w_best[3]
lines(x, a_best*x+b_best,col ="red")
```

###############

SGD Logistic
################